#https://hub.docker.com/repository/docker/hotandcool/app
FROM node:12.18.2-stretch
WORKDIR /app
# Dependencies/library
COPY package*.json ./
RUN npm install
# Copy All file
COPY . .
EXPOSE 4000
CMD [ "npm"", "start" ] 