#https://hub.docker.com/repository/docker/pamutakea/app
FROM node:12.18.2-stretch
WORKDIR /app
#Dependencies/Library
COPY package*.json ./
RUN npm install
#Copy All Files
COPY . .
EXPOSE 4000
CMD [ "npm", "start" ]